= Modulhandbuch

== Problemstellung

Das aktuelle Modulhandbuch ist ein großes Word-Dokument.
Das komplette Dokument muss angepackt werden um z.B ein Datum zu ändern.
Die Darstellung der Module ist unübersichtlich.
Es gibt keine Suchfunktion, was den oberen Punkt schwerer wiegen lässt.
In einem Semster kann man sehen, welche Module angeboten werden, aber nicht,
ob alle Teile des Moduls in dem Semster verfügbar sind.
Die Angabe in welchen Semster das Modul verfügbar ist, liegt in einer seperaten Datei.
Es gibt keinen Mechanismus, der anzeigt, dass zu viele oder zu wenige Module in
Bachelor- oder Masterstudiengängen angeboten werden und es so zu einem Ungleichgewicht kommt.

== Ziele und Lösungen

Dozenten können Module erstellen oder einzelne Aspekte des Moduls ändern.
Der Administrator bekommt diese Anträge und kann diese bestätigen oder abändern und dann bestätigen.
Erst nachdem der Administrator den Antrag reviewt hat, wird das Modul für die Nutzer angezeigt.
Der Nutzer kann mit einer Volltextsuche und Filterfunktion seine Module finden und auswählen,
damit er sie später als PDF herunterladen kann.
Es gibt eine dynamische Semesterübersicht, die anzeigt welche Module in dem ausgewählten Semester verfügbar sind.

