[[section-building-block-view]]
== Bausteinsicht

Dieser Abschnitt beschreibt die Aufteilung der Anwendung

=== Whitebox Gesamtsystem

_**<Übersichtsdiagramm>**_

Begründung:: _<Erläuternder Text>_

Enthaltene Bausteine:: _<Beschreibung der enthaltenen Bausteine (Blackboxen)>_

Wichtige Schnittstellen:: _<Beschreibung wichtiger Schnittstellen>_

== Volltextsuche

 Zweck/Verantwortung::

_Die Suche soll dem Nutzer eine Möglichkeit geben, durch das Eingeben von Stichworten eine Liste von Modulen zu erhalten._

 Schnittstelle::

 _Die Schnittstelle für den Nutzer ist die Suchleiste, also die GET Anfrage an den SearchController._

 Qualitäts-/Leistungsmerkmale::
 _Die Suche soll auch mit Teilworten fertig werden; sucht der Nutzer also nach dem Keyword "Architektur", so muss die Suche auch den Eintrag "Architekturformen" finden können._

== Erstellen von Anträgen

 Schnittstelle(n)::

 _Die Schnittstellen liegen hier in der View der Modulbeauftragten und der Admin View. Nur von diesen beiden Seiten können nach Authentifizierung des Nutzers Anträge erstellt werden. Die Anträge können zum Erstellen von Modulen oder zur Änderung ebendieser verwendet werden._

 Qualitäts-/Leistungsmerkmale::

 _Anträge sollen zu jeder Zeit erstellbar sein und gespeichert werden._

== Annehmen von Anträgen

Schnittstelle(n)::

 _Die Schnittstellen liegen hier in der View des Administrators Nur von dieser beiden Seite aus können nach Authentifizierung des Nutzers Anträge bearbeitet und angenommen werden.
 Es kann sich um das Annehmen von Modifikations Anträgen, also einer bearbeitung eines bereits bestehenden Moduls, und um Kreations Anträge, also das neu erstellen eines Moduls, handeln._


Qualitäts-/Leistungsmerkmale::

 _Anträge sollen zu jeder Zeit annehmbar sein. Der Administrator hat die Möglichkeit Bestandteile zu bearbeiten_

== PDF Download

 Schnittstelle::
 _Das komplette Modulhandbuch wird auf der Hauptseite zum Download angeboten._

 Qualitäts-/Leistungsmerkmale::

 _Das aktuelle Modulhandbuch im PDF-Format soll zu jeder Zeit in ansehnlicher Formatierung verfügbar sein._

== REST-API

 Schnittstelle::
 _Die aktuellen Module werden per HTTP GET-Request zur Verfügung gestellt._

 Qualitäts-/Leistungsmerkmale::

 _Die Modulinformationen sollen zu jeder Zeit in korrekt formatiertem JSON für den API-Nutzer abrufbar sein. Der Nutzer soll genau spezifizieren können, welche Informationen er benötigt._

== Volltextsuche Blackbox

 Suche im Detail::

 _In der index.html gibt es ein Formular, mit dem ein Request Parameter (searchField) durch eine GET-Anfrage an den SearchController geschickt wird.
 Die Methode search() im Controller ruft dann die Methode search() im SearchService auf. Der searchField Parameter wird dabei übergeben.
 Diese Methode wendet durch Hibernate Search eine Suchanfrage auf die Datenbank an. Hibernate Search hat beim Start des Programms die relevanten Felder indexiert und aktualisiert sich bei neu hinzugefügten (oder geänderten) Modulen selbst.
 Außerdem werden beim Indexieren alle nicht sichtbaren Module ignoriert.
 Der Index wird genutzt, um mit der Suchanfrage die relevanten Felder in den Modulen zu durchsuchen. Wildcards ermöglichen, dass Teilworte erkannt werden. Die Methode gibt eine Liste zurück, welche als Modellattribut in searchresults.html übergeben wird.
 Der Nutzer wird dann auch auf searchresults weitergeleitet und bekommt die Liste als Linksammlung angezeigt.
 Die Links leiten den Nutzer weiter auf die Moduldetails._

== PDF-Download Blackbox

 PDF-Generierung im Detail::

 _In der index.html gibt es neben der Suchleiste einen PDF-Knopf, mit dem per GET-Request auf /module/pdf die PDF-Generierung des aktuellen Modulhandbuchs gestartet wird.
 Im PdfDownloadController wird nun über den ModulService die aktuelle Liste aller sichtbaren Module abgerufen und vom PdfDownloadController an die Methode generatePdf des PdfServices weitergegeben.
 Diese Funktion wandelt die Modulobjekte nun in PdfModulWrapper-Objekte um, sodass alle benötigten Zeichenketten direkt von Thymeleaf ausgelesen werden können.
 Die PdfModulWrapper-Liste sowie die Modulkategorien, als auch das aktuelle Semester werden per Context dann an die Thymeleaf TemplateEngine weitergegeben, welche dann mit Hilfe des HTML-Templates modulhandbuch.html das Modulhandbuch zuerst im HTML-Format baut. Dabei wird auch ein Inhaltsverzeichnis automatisch generiert und alle Felder des Modulhandbuchs automatisch befüllt, wobei - analog zur Webansicht - innerhalb von Modulen mehrere Unterveranstaltungen existieren können.
 Attribute aus den Modulobjekten, welche auch Markdown-Support bieten sollen, werden vor der Injektion mit Hilfe des PdfModulWrappers bzw. des PdfVeranstaltungWrappers mit Verweis auf die statische markdownToHTML-Funktion des htmlServices in valides HTML umgewandelt.
 Nach der Generierung des vollständigen HTML-Dokumentes wird dieses an die htmlToPdf-Methode aus dem htmlService übergeben, welche mit Hilfe des flexmark-Paketes dieses dann in einen PDF-Bytestrom umwandelt.
 Dieser ByteStrom wird zu guter Letzt dem PdfDownloadController zurückgegeben und dieser stellt dem Benutzer dann das fertige PDF-Modulhandbuch zum Download zur Verfügung und schließt den Strom wieder._

== REST-API Blackbox

 REST-API im Detail::

 _Über /module/api ist die Schnittstelle verfügbar, bei der über query die genauen Attribute spezifiziert werden, die der Nutzer abrufen möchte.
 GraphQL fängt diese Anfrage über den GraphQLProvider ab und prüft ob die Anfrage korrekt gestellt wurde.
 Die möglichen Anfragen wurden dabei in der schema.graphqls Datei spezifiziert und können über das ebenso eingebundene GraphiQL über /module/graphiql erkundet werden.
 Ist die Anfrage fehlerhaft, so gibt GraphQL eine Fehlermeldung zurück.
 Bei korrekt gestellter Anfrage sammelt GraphQL über die GraphQlDataFetchers die angeforderten Informationen und nutzt dabei den ModulService, welcher die Daten aus der Datenbank ausliest.
 Die vom ModulService zurückgegebenen Modulobjekte werden mit Hilfe der schema.graphqls und eigenst definierter GraphQL-scalars (LocalDateTime und Modulkategorie) in einen JSON-String umgewandelt.
 Dieser String wird dem Nutzer dann in der HTTP-Response zurückgegeben._

== Anträge für Erstellung Blackbox

Anträge für Erstellung im Detail::

_Als Organisatoren eingeloggte Nutzer können unter dem Reiter "Module bearbeiten" Anträge zur Erstellung oder Bearbeitung von Modulen hinzufügen.
Für die Erstellung eines Antrags für ein neues Modul wird hierfür zunächst der Button "Modul hinzufügen" angeklickt, anschließend öffnet sich ein Bootstrap-Modal, in welchem der Nutzer die Anzahl der Veranstaltungen in dem neuen Modul angeben muss.
Die kleinste mögliche Eingabe für dieses Input-Feld ist hierbei 1. Beim Bestätigen des "Fortfahren"-Buttons wird ein GET-Request an den ModulerstellungController mit der entsprechenden Veranstaltungsanzahl gesendet.
In der Controller-Methode wird anschließend durch die initializeEmptyWrapper()-Methode ein ModulWrapper erstellt, der neben einer leeren Instanz der Modul-Entity die variabel großen Unterfelder und Unter-Unterfelder von Modul (Veranstaltungen und innerhalb von Veranstaltung Veranstaltungsformen und Zusatzfelder) erweitert durch leere Instanzen auf die im ModulWrapperService festgelegten Standardgrößen dieser Unter-Unterfelder enthält.
Bei der anschließenden Weitergabe dieses Wrappers an modulerstellung.html wird dann ein leeres Formular durch Iteration mittels Thymeleaf über die im ModulWrapper enthaltenen Listen generiert, das dadurch die festgelegte Anzahl an ausfüllbaren Input-Feldern hat.
Anschließend wird das durch Thymeleaf in den jeweiligen Feldern befüllte ModulWrapper-Objekt per POST-Request wieder an den ModulerstellungController zurückgegeben und mithilfe der readModulFromWrapper()-Methode wieder entpackt, die Unter- und Unter-Unterfelder korrekt auf die eingegebenen Daten gesetzt und das so erstellte Modul-Objekt mithilfe von AntragService verpackt in einen Antrag in der Datenbank gespeichert.
Der Antrag ist ab diesem Zeitpunkt als offener Antrag für Administratoren einsehbar.
Es wird geprüft, ob es sich beim Nutzer um einen Administrator handelt und in diesem Fall der Antrag direkt genehmigt, das Modul in der Datenbank gespeichert und auf sichtbar gesetzt._

== Anträge für Bearbeitung Blackbox

Anträge für Bearbeitung im Detail::

_Für die Erstellung eines Änderungsantrags für ein existierendes Modul wird aus einer Liste der sichtbaren Module ein Modul angeklickt.
Beim Anklicken des Moduls wird ein GET-Request an den ModulerstellungController mit der entsprechenden Modul-ID gesendet.
Es wird aus der Datenbank das entsprechende Modul ausgegeben und an die Methode initializePrefilledWrapper() weitergegeben.
In dieser wird ähnlich dem oben beschriebenen Vorgehen ein ModulWrapper mit auf in ModulWrapperService festgelegte Größen Listen mit leeren Instanzen aufgefüllt, wobei im Unterschied zur initializeEmptyWrapper()-Methode die existierenden Einträge in den Listen erhalten bleiben und ihnen leere Instanzen angehangen werden, bis die Listen die richtige Größe haben.
Dieser Wrapper wird neben der Modul-ID wieder an die selbe html-Datei wie bei der Erstellung gegeben und öffnet das selbe Formular, allerdings sind in diesem Fall die Felder (bis auf die auffüllenden leeren Listen-Einträge) vorausgefüllt.
Zusammen mit der Modul-ID wird der abgeänderte ModulWrapper per POST-Request an den ModulerstellungController zurückgeschickt.
Da es sich um einen Änderungsantrag handelt, müssen nun die Änderungen zum alten Modul festgestellt werden.
Hierzu wird zunächst mithilfe der ID das alte Modul aus der Datenbank geholt und das neue Modul mit Hilfe von readModulFromWrapper() aus dem ModulWrapper ausgelesen.
Anschließend werden mithilfe von calculateModulDiffs() aus ModulService die beiden Module auf relevante (d.h. nicht z.B. automatisch generierte Zeitstempel betreffende) Unterschiede untersucht und in Form eines Differenzmoduls (d.h. einer Modul-Instanz, bei der Felder ohne Unterschiede den Wert null und Felder mit Änderungen den Wert nach der Änderung haben) ausgibt.
Wenn in diesem Differenzmodul Änderungen festgestellt wurden, wird der Änderungsantrag in der Datenbank gespeichert und ist ab diesem Zeitpunkt als offener Antrag für Administratoren einsehbar.
Es wird geprüft, ob es sich beim Nutzer um einen Administrator handelt und in diesem Fall der Antrag direkt genehmigt und das Modul in der Datenbank geupdatet._


== Annahme von Anträgen für Erstellung Blackbox

*Reiter Anträge -> AdministratorController* ::
Durch drücken auf den Reiter "Anträge", angemeldet mit der Rolle "Sekretariat"
, wird ein GET-Request ausgelöst welcher im AdministratorController von der Methode administrator behandelt wird.
Diese Methode fügt dem Model drei verschiedene Objekte hinzu. Ein Datetime Formatter Objekt um in der Liste der offenen Anträge das
Erstellungsdatum der Anträge einheitlich darzustellen, ein Account Objekt für den Zugang zu Keycloak und somit die Authentifizierung als
Rolle Sekretariat und eine Liste aller offenen Anträge geordnet nach dem Erstellungsdatum. Für diese wird im antragService
die Methode getAlleOffenenAntraegeGeordnetDatum aufgerufen die über die Methoden getAlleAntraegeGeordnetDatum und getAlleAntraege durch das antragRepository
auf die Datenbank zugreift.
Anschließend wird die html administrator returnd.
*adminstrator.html -> AntragdetailsController*::
Die administrator.html Seite zeigt dem Nutzer nun eine geordnete Liste aller offenen Anträge mit zugehörigem Erstellungsdatum und
dem Namen des Antragstellers. Je nachdem ob es sich um einen Modifikations- oder Kreations Antrag handelt wird durch das Bestätigen eines Links
eine Request Methode im AntragdetaislController angesprochen. Mit übergeben wird die ID des Antrages als Pathvariabel.

*AntragdetailsController Kreation -> angtragdetails.html*::
Mit Hilfe der übergebenen Antragsid wird aus dem antragService durch die Methode getAntragByid() der zugehörige Antrag ausgelesen.
Das bearbeitete Modul, welches sich in dem Antragsobjekt als Json befindet, wird mithilfe der jsonObjectToModul Methode aus dem JsonService
in einem Modul "modulAusAntrag" abgespeichert. Für die Umsetzung der Anzeige aller Felder aus dem Modul im Frontend wird
das Modul anschließend in einem ModulWrapper verpackt. Dies geschieht durch Aufruf der Methode initializePrefilledWrapper() aus dem ModulWrapperService.
Diese Methode befüllt ein ModulWrapper Objekt mit dem Modul und jeweils einem Array an Listen von Veranstaltungen,
Veranstaltungsformen und Zusatzfeldern.
Dieses Wrapper Objekt wird neben der Antrags ID, dem Account für Keycloak und erneut dem Wrapper Objekt dem Model übergeben.
Das Wrapper Objekt wird zweifach übergeben da Kreation und Modifikation sich auf dieselbe html Datei ( antragdetails.html) beziehen
und bei der Modifikation zwei Modul Wrapper mithilfe von Thymeleaf verglichen werden.
Anschließend wird die html antragdetails returned.

*AntragdetailsController Modifikation -> antragdetails.html*::
Der Fall der Modifikation wird im AntragdetailsController ähnlich wie der Fall der Kreation gehandhabt.
Da im Frontend allerdings Änderungen zwischen dem Modul vor und nach Ausführung der Änderungen angezeigt werden sollen wird in diesem
Fall das Alte Modul kopiert und die Änderungen aus dem Antrag mithilfe der Methode applyAntragOnModul aus dem Modulservice angewendet.
Dem Model werden dann der Account für Keycloak, die Antragsid und die beiden Modul Wrapper objekte hinzugefügt.

*antragdetails.html -> AntragdetailsController*::
In der antragdetails.html wird dem User nun das übergebene ModulWrapper Objekt angezeigt.
Mit Hilfe von th:object und th:field werden Änderungen direkt im ModulWrapper Objekt abgespeichert. Für den Fall der Modifikation
werden Unterschiede zwischen der alten und neuen Version durch eine th:if Abfrage farblich makiert.
Nachdem der Antrag geprüft und gegebene Falls verändert wurde, schickt der Nutzer durch Bestätigen
des "Antrag annehmen" Buttons einen Post-Request der im AntragdetailsController entgegengenommen wird.
Dieser beinhaltet die antragsId als Pathvariable und das ModulWrapper Objekt mit allen Änderungen.

*AntragdetailsController -> Speicherung in der Datenbank*::
In der PostMapping Methode antragAnnehmen wird zuerst das Modul mit Hilfe der Methode readModulFromWrapper aus dem
ModulWrapperService ausgepackt. Durch diese Methode werden die Arrays an Listen wieder in Sets in dem modul abgespeichert welches dann
returnt wird.
Der ursprüngliche Antrag wird nun mithilfe der übergebenen Antragsid  und
der Methode getAntragById aus dem antragService in einem Antrags Objekt abgespeichert.
Das Modul wird mithilfe der Methode setJsonModulAenderung und modulToJsonObject aus dem Json Service wieder im Antrag abgespeichert.
Wenn es sich um eine Kreation handelt, das Modul also noch keine ID hat, weil es nicht in der Datenbank steht (auto generated ID),
wird die Methode approveModulCreationAntrag aus dem AntragService aufgerufen.
In dieser Methode wird nun das Modul, welches noch in Form eines Json im Antrag steckt mithilfe des JsonServices in ein Modul
abgespeichert. Anschließend wird das Modul durch das modulSnapshotRepository in der Datenbank abgespeichert, das Genehmigungsdatum
und die ModulId im Antrag gesetzt und auch dieser durch das antragRepository abgespeichert.

Handelt es sich um eine Modifikation wird die Methode approveModifikationAntrag aus dem antragService aufgerufen.
Diese Methode überträgt die Änderungen aus dem Antrag auf das alte Modul, welche in der Datenbank gespeichert ist, setzt das Datum der Genehmigung im Antrag, und speichert anschließend
auch den Antrag mit Hilfe des antragRepositorys in der Datenbank.

Anschließend wird der Nutzer aus die administrator.html, also die Übersicht aller offenen Anträge, redirected.


==== <Name Blackbox n>

_<Blackbox-Template>_


==== <Name Schnittstelle 1>

...

==== <Name Schnittstelle m>

=== Ebene 2



==== Whitebox _<Baustein 1>_



_<Whitebox-Template>_

==== Whitebox _<Baustein 2>_

_<Whitebox-Template>_

...

==== Whitebox _<Baustein m>_

_<Whitebox-Template>_

=== Ebene 3



==== Whitebox <_Baustein x.1_>



_<Whitebox-Template>_

==== Whitebox <_Baustein x.2_>

_<Whitebox-Template>_

==== Whitebox <_Baustein y.1_>

_<Whitebox-Template>_
