[[section-building-block-view]]
== Bausteinsicht

Dieser Abschnitt beschreibt die Aufteilung der Anwendung

=== Whitebox Gesamtsystem



_**<Übersichtsdiagramm>**_

Begründung:: _<Erläuternder Text>_

Enthaltene Bausteine:: _<Beschreibung der enthaltenen Bausteine (Blackboxen)>_

Wichtige Schnittstellen:: _<Beschreibung wichtiger Schnittstellen>_

== Volltextsuche

 Zweck/Verantwortung::

_Die Suche soll dem Nutzer eine Möglichkeit geben durch das eingeben von Stichworten eine Liste von Modulen zu erhalten._

 Schnittstelle(n)::

 _Die Schnittstelle für den Nutzer ist die Suchleiste, also die GET Anfrage an den SearchController, der dann die Methode search im Suchservice aufruft._

 Qualitäts-/Leistungsmerkmale::
 _Die Suche soll auch mit Teilworten fertig werden, z.B wenn der Nutzer Architektur eingibt muss die Suche auch Architekturformen finden können._

==== <Name Blackbox 2>

_<Blackbox-Template>_

==== <Name Blackbox n>

_<Blackbox-Template>_


==== <Name Schnittstelle 1>

...

==== <Name Schnittstelle m>

=== Ebene 2



==== Whitebox _<Baustein 1>_



_<Whitebox-Template>_

==== Whitebox _<Baustein 2>_

_<Whitebox-Template>_

...

==== Whitebox _<Baustein m>_

_<Whitebox-Template>_

=== Ebene 3



==== Whitebox <_Baustein x.1_>



_<Whitebox-Template>_

==== Whitebox <_Baustein x.2_>

_<Whitebox-Template>_

==== Whitebox <_Baustein y.1_>

_<Whitebox-Template>_
